// This is exaple file. rename this file to db.properties
// for db connection to your local host.
// And then fill in the following details
// Run schema.sql in your sqlworkbench begfore running the
// app so it can connect to database

db.url = jdbc:mysql://localhost:3306/wirasat
db.user =
db.password =

// IMPORTANT: After filling in the info add this file to \
// .gitignore to prevent pushing your credentials on github